version: "3"
services:
  this_jupyter:
    build:
      context: ./docker/jupyter/
      dockerfile: Dockerfile
    volumes:
      - .:/home/jovyan/
    ports:
      - 8888:8888
  this_postgres:
    build: ./docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
volumes:
  postgres_data:
